spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    jedis:
      pool:
        max-wait: 1000ms
        min-idle: 10
        max-idle: 100
        max-active: 100
    port: 6379
    host: localhost
    database: 1
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.woniu.secondkill.pojo
logging:
  level:
    com.woniu.secondkill.dao: debug
template:
  path: e:/template/goods/showdetails/